core/urls.py
from django.urls import path

from core import views


app_name = 'core'


urlpatterns = [
    path('', views.home, name='home'),
]

project/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('userauths.urls')),
    path('', include('core.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userauths/urls.py
from django.urls import path

from userauths import views


app_name = 'userauths'


urlpatterns = [
    path('sign-up/', views.register_view, name='sign-up'),
    path('sign-in/', views.login_view, name='sign-in'),
    path('sign-out/', views.logout_view, name='sign-out'),
    # path('profile-edit/', views.kyc_registration, name='kyc-registration'),
    path('account/', views.account, name='account'),
    path('delete-account/', views.delete_account, name='delete-account'),
    path('change-password/', views.change_password, name='change-password'),
]

userauths/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save
from django.utils.translation import gettext_lazy as _


import uuid
from shortuuid.django_fields import ShortUUIDField

# Create your models here.


def user_directory_path(instance, filename):
    ext = filename.split(".")[-1]
    filename = "%s_%s" % (instance.id, ext)
    return "user_{0}/{1}".format(instance.user.id, filename)



class User(AbstractUser):
    frist_name = models.CharField(_('Frist Name'), max_length=255)
    last_name = models.CharField(_('Last Name'), max_length=255)
    username = models.CharField(_('Username'), max_length=255)
    email = models.EmailField(_('Email'), unique=True)
    phone = models.CharField(_("Phone Number"),max_length=50, null=True, blank=True)
    company = models.CharField(_('Company'), max_length=255, null=True, blank=True)
    date_of_birth = models.DateTimeField(_('Date Of Birth'), auto_now_add=False, blank=True, null=True)
    is_staff = models.BooleanField(_('Is Staff'), default=False)
    is_superuser = models.BooleanField(_('Super User'), default=False)


    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return str(self.username)
    


ACCOUNT_STATUS = (
    ("active", "Active"),
    ("pending", "Pending"),
    ("in-active", "In-active")
)

class Account(models.Model):
    id = models.UUIDField(primary_key=True, unique=True, default=uuid.uuid4, editable=False)
    user =  models.OneToOneField(User, on_delete=models.CASCADE)
    account_number = ShortUUIDField(unique=True,length=10, max_length=25, prefix="217", alphabet="1234567890")
    account_id = ShortUUIDField(unique=True,length=7, max_length=25, prefix="DEX", alphabet="1234567890")
    pin_number = ShortUUIDField(unique=True,length=4, max_length=7, alphabet="1234567890") #2737
    red_code = ShortUUIDField(unique=True,length=10, max_length=20, alphabet="abcdefgh1234567890")
    account_status = models.CharField(max_length=100, choices=ACCOUNT_STATUS, default="in-active")
    date = models.DateTimeField(auto_now_add=True)
    kyc_submitted = models.BooleanField(default=False)
    kyc_confirmed = models.BooleanField(default=False)
    recommended_by = models.ForeignKey(User, on_delete=models.DO_NOTHING, blank=True, null=True, related_name="recommended_by")
    review = models.CharField(max_length=100, null=True, blank=True, default="Review")

    
    class Meta:
        ordering = ['-date']

    def __str__(self):
        return f"{self.user}"
    

def create_account(sender, instance, created, **kwargs):
    if created:
        Account.objects.create(user=instance)

def save_account(sender, instance,**kwargs):
    instance.account.save()

post_save.connect(create_account, sender=User)
post_save.connect(save_account, sender=User)



MARITAL_STATUS = (
    ("married", "Married"),
    ("single", "Single"),
    ("other", "Other")
)

GENDER = (
    ("male", "Male"),
    ("female", "Female"),
    ("other", "Other")
)



# class KYC(models.Model):
#     id = models.UUIDField(primary_key=True, unique=True, default=uuid.uuid4, editable=False)
#     user =  models.OneToOneField(User, on_delete=models.CASCADE)
#     account =  models.OneToOneField(Account, on_delete=models.CASCADE, null=True, blank=True)
#     frist_name = models.CharField(max_length=1000)
#     last_name = models.CharField(max_length=1000)
#     image = models.ImageField(upload_to="kyc", default="default.jpg")
#     marrital_status = models.CharField(choices=MARITAL_STATUS, max_length=40)
#     gender = models.CharField(choices=GENDER, max_length=40)
#     date_of_birth = models.DateTimeField(auto_now_add=False)
#     company = models.CharField(max_length=100)
#     mobile = models.CharField(max_length=1000)
#     date = models.DateTimeField(auto_now_add=True)


#     def __str__(self):
#         return f"{self.user}"    

    
#     class Meta:
#         ordering = ['-date']

userauths/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm , PasswordChangeForm
from django.forms import ImageField, FileInput, DateInput


from .models import User 


class UserRegisterForm(UserCreationForm):
    frist_name = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Frist Name"}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Last Name"}))
    username = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Username"}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={"placeholder":"Email"}))
    phone = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Phone"}))
    date_of_birth = forms.DateTimeField(widget=forms.DateInput(attrs={"type": "date", "placeholder": "Date of Birth"}))
    company = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Company"}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder":"Password"}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder":"Confirm Password"}))

    class Meta:
        model = User
        fields = ['frist_name', 'last_name', 'username', 'email', 'phone', 'date_of_birth', 'company', 'password1', 'password2']



class DateInput(forms.DateInput):
    input_type = 'date'


# class KYCForm(forms.ModelForm):
#     image = ImageField(widget=FileInput)

#     class Meta:
#         model = KYC
#         fields = [ 'frist_name', 'last_name' , 'image', 'marrital_status', 'gender',  'date_of_birth', 'company' , 'mobile']
#         widgets = {
#             "frist_name": forms.TextInput(attrs={"placeholder":"Frist Name"}),
#             "last_name": forms.TextInput(attrs={"placeholder":"Last Name"}),
#             "mobile": forms.TextInput(attrs={"placeholder":"Mobile Number"}),
#             "company": forms.TextInput(attrs={"placeholder":"Company"}),
#             'date_of_birth':DateInput
#         }


class UserPasswordChangeForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super(UserPasswordChangeForm, self).__init__(*args, **kwargs)
        self.fields['old_password'].widget.attrs['placeholder'] = 'Old Password'
        self.fields['new_password1'].widget.attrs['placeholder'] = 'New Password'
        self.fields['new_password2'].widget.attrs['placeholder'] = 'Confirm New Password'

userauths/views.py
from django.shortcuts import render , redirect
from django.contrib.auth import authenticate, login, logout , update_session_auth_hash
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm

from .models import User , Account 
from .forms import UserRegisterForm  , UserPasswordChangeForm 



# Create your views here.


def register_view(request):
    if request.user.is_authenticated:
        messages.warning(request, "You are already logged in.")
        return redirect("userauths:account")
    
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.username = form.cleaned_data['username']  
            new_user.save()
            
            messages.success(request, f'Account created for {new_user.username}! You are now able to log in.')
            
            new_user = authenticate(
                request,
                username=form.cleaned_data['email'],
                password=form.cleaned_data['password1'],
            )
            
            if new_user is not None:
                login(request, new_user)
                return redirect("userauths:account")
            else:
                messages.error(request, "Authentication failed. Please log in manually.")
                return redirect("userauths:login")
    else:
        form = UserRegisterForm()
    
    context = {
        'form': form,
    }
    return render(request, 'userauths/sign-up.html', context)



def login_view(request):
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']

        user = authenticate(email=email, password=password)

        try:
            user = User.objects.get(email=email)
            user = authenticate(request, email=email, password=password)

            if user is not None: # if there is a user
                login(request, user)
                messages.success(request, "You are logged.")
                return redirect("userauths:account")
            else:
                messages.warning(request, "Username or password does not exist")
                return redirect("userauths:sign-in")
        except:
            messages.warning(request, "User does not exist")

    if request.user.is_authenticated:
        messages.success(request, 'You are already logged in')
        return redirect("userauths:account")

    return render(request, 'userauths/sign-in.html')


def logout_view(request):
    logout(request)
    messages.success(request, 'You have been logged out')
    return redirect('userauths:sign-in')



# @login_required
# def kyc_registration(request):
#     user = request.user
#     account = Account.objects.get(user=user)

#     try:
#         kyc = KYC.objects.get(user=user)
#     except:
#         kyc = None
    
#     if request.method == "POST":
#         form = KYCForm(request.POST, request.FILES, instance=kyc)
#         if form.is_valid():
#             new_form = form.save(commit=False)
#             new_form.user = user
#             new_form.account = account
#             new_form.save()
#             messages.success(request, "KYC Form submitted successfully, In review now.")
#             return redirect("core:home")
#     else:
#         form = KYCForm(instance=kyc)
#     context = {
#         "account": account,
#         "form": form,
#         "kyc": kyc,
#     }
#     return render(request, "userauths/kyc-form.html", context)



@login_required
def account(request):
    if request.user.is_authenticated:
        try:
            kyc = KYC.objects.get(user=request.user)
        except:
            messages.warning(request, "You need to submit your kyc")
            # return redirect("userauths:kyc-registration")
            return redirect("core:home")
        
        account = Account.objects.get(user=request.user)
    else:
        messages.warning(request, "You need to login to access the dashboard")
        return redirect("userauths:sign-in")

    context = {
        "kyc":kyc,
        "account":account,
    }
    return render(request, "userauths/account.html", context)



@login_required
def delete_account(request):
    user = request.user
    if request.method == "POST":
        Account.objects.filter(user=user).delete()
        KYC.objects.filter(user=user).delete()

        user.delete()
        messages.success(request, "Your account has been deleted successfully.")
        return redirect("userauths:sign-in")

    return render(request, "userauths/delete_account.html")



@login_required
def change_password(request):
    if request.method == 'POST':
        form = UserPasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, 'Your password has been updated successfully!')
            return redirect('userauths:account')
        else:
            messages.error(request, 'Please correct the errors below.')
    else:
        form = UserPasswordChangeForm(request.user)

    return render(request, 'userauths/change_password.html', {'form': form})

userauths/templates/userauths/111.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete Account</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600&display=swap" rel="stylesheet">
    <style>
        body {
            background: linear-gradient(to right, #1e3c72, #2a5298);
            color: #fff;
            font-family: 'Poppins', sans-serif;
        }
        .card {
            background: rgba(255, 255, 255, 0.1);
            border: none;
            backdrop-filter: blur(20px);
            border-radius: 15px;
            padding: 20px;
            transition: transform 0.3s ease;
            box-shadow: 0 4px 10px rgba(0, 0, 0, 0.2);
        }
        .card:hover {
            transform: scale(1.03);
        }
        .btn-danger {
            background-color: #ff4b5c;
            border: none;
            transition: all 0.3s ease;
        }
        .btn-danger:hover {
            background-color: #e63950;
            transform: scale(1.05);
        }
        .btn-info {
            background-color: #17c3b2;
            border: none;
            transition: all 0.3s ease;
        }
        .btn-info:hover {
            background-color: #149e91;
            transform: scale(1.05);
        }
    </style>
</head>
<body>
    <div class="container d-flex justify-content-center align-items-center vh-100">
        <div class="card shadow-lg text-center" style="max-width: 400px;">
            <div class="card-body">
                <h2 class="text-warning fw-bold">Are you sure?</h2>
                <p class="text-light">This action is irreversible. All your data will be permanently deleted.</p>
                
                <form method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger btn-lg w-100 mb-2 shadow">
                        Yes, Delete My Account
                    </button>
                    <a href="{% url 'userauths:account' %}" class="btn btn-info btn-lg w-100 shadow">
                        Cancel
                    </a>
                </form>
            </div>
        </div>
    </div>
</body>
</html>

userauths/templates/userauths/kyc-form.html
{% extends "auth_base.html" %}
{% load static %}

{% block content %}
    <head>
        <style>
            #id_image{
                background-color: #432f9f;
                /* border: 1px solid #e2e9f3; */
                border-radius: 4px;
                height: 50px;
                width: 100%;
                color: #ffffff;
            }
            #id_image::file-selector-button{
                border: none;
                border-radius: 7px;
                color: 432f9f;
                background-color: #ffffff;
                /* border: 1px solid #595ef1bd; */
                height: 30px;
                cursor: pointer;
                transition: all .25s ease-in;
            }
            #id_image::file-selector-button:hover,
            #id_identity_type::file-selector-button:hover{
                background-color: #fff;
                color: #565A90;
                transition: all .25s ease-in;
            }
            
            #id_identity_image{
                background-color: #432f9f;
                /* border: 1px solid #e2e9f3; */
                border-radius: 4px;
                height: 50px;
                width: 100%;
                color: #ffffff;
            }
            #id_identity_image::file-selector-button{
                border: none;
                border-radius: 7px;
                color: 432f9f;
                background-color: #ffffff;
                /* border: 1px solid #595ef1bd; */
                height: 30px;
                cursor: pointer;
                transition: all .25s ease-in;
            }
            #id_identity_image::file-selector-button:hover{
                background-color: #fff;
                color: #565A90;
                transition: all .25s ease-in;
            }
        </style>
    </head>
    
    <!-- Dashboard Section start -->
    <section class="dashboard-section body-collapse account">
        <div class="overlay pt-120">
            <div class="container-fruid">
                <div class="main-content">
                    <div class="row">
                        <div class="col-xxl-3 col-xl-4 col-md-6">
                            <div class="owner-details">
                                <div class="profile-area">
                                    <div class="profile-img">
                                        {% if kyc.image %}
                                            <img src="{{user.kyc.image.url}}" style="width: 100px; height: 100px; border-radius: 50%; object-fit: cover;" alt="image">
                                        {% else %}
                                            <img src="{% static 'assets1/images/default.jpg' %}" style="width: 100px; height: 100px; border-radius: 50%; object-fit: cover;" alt="image">
                                        {% endif %}
                                    </div>
                                    <div class="name-area">
                                        <h6>{{request.user.username|title}}</h6>
                                        <p class="text-danger">{{ request.user.account.account_status|title }}</p>
                                    </div>
                                </div>
                                <div class="owner-info">
                                    <ul>
                                        <li>
                                            <p>Account ID:</p>
                                            <span class="mdr">{{ request.user.account.account_id }}</span>
                                        </li>
                                        <li>
                                            <p>Joined:</p>
                                            <span class="mdr">{{request.user.account.date|date:"d M, Y"}}</span>
                                        </li>
                                    </ul>
                                </div>
                                <div class="owner-action">
                                    <a href="{% url 'userauths:sign-out' %}">
                                        <img src="{% static 'assets1/images/icon/logout.png' %}" alt="image">
                                        Logout
                                    </a>
                                    <a href="{% url 'userauths:delete-account' %}" class="delete">
                                        <img src="{% static 'assets1/images/icon/delete-2.png' %}" alt="image">
                                        Delete Account
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="col-xxl-9 col-xl-8">
                            <div class="tab-main">
                                <ul class="nav nav-tabs" role="tablist">
                                    <li class="nav-item" role="presentation">
                                        <button class="nav-link active text-center" id="account-tab" data-bs-toggle="tab"
                                            data-bs-target="#account" type="button" role="tab" aria-controls="account"
                                            aria-selected="true">Update Profile</button>
                                    </li>
                                    
                                </ul>
                                <div class="tab-content mt-40">
                                    <div class="tab-pane fade show active" id="account" role="tabpanel"
                                        aria-labelledby="account-tab">
                                        <form method="POST" enctype="multipart/form-data">
                                            {% csrf_token %}
                                            <div class="upload-avatar">
                                                <div class="avatar-left d-flex align-items-center">
                                                    <div class="profile-img">
                                                        {% if kyc.image %}
                                                            <img src="{{user.kyc.image.url}}" style="width: 100px; height: 100px; border-radius: 50%; object-fit: cover;" alt="image">
                                                        {% else %}
                                                            <img src="{% static 'assets1/images/default.jpg' %}" style="width: 100px; height: 100px; border-radius: 50%; object-fit: cover;" alt="image">
                                                        {% endif %}
                                                    </div>
                                                    <div class="instraction">
                                                        <h6>Your Avatar</h6>
                                                    </div>
                                                </div>
                                                <div class="avatar-right">
                                                    {{form.image}}
                                                </div>
                                            </div>
                                        
                                            <div class="row justify-content-center">
                                                <div class="col-md-6">
                                                    <div class="single-input">
                                                        <label for="fName">Frist Name</label>
                                                        {{form.frist_name}}
                                                    </div>
                                                </div>
                                                

                                                <div class="col-md-6">
                                                    <div class="single-input">
                                                        <label for="fName">Last Name</label>
                                                        {{form.last_name}}
                                                    </div>
                                                </div>

                                                <div class="col-md-6">
                                                    <div class="single-input">
                                                        <label for="fName">Mobile Number</label>
                                                        {{form.mobile}}
                                                    </div>
                                                </div>
                                                <div class="col-md-6">
                                                    <div class="single-input">
                                                        <label for="fName">Company</label>
                                                        {{form.company}}
                                                    </div>
                                                </div>
                                            
                                                <div class="col-md-12">
                                                    <div class="single-input">
                                                        <label for="fName">Date Of Birth</label>
                                                        {{form.date_of_birth}}
                                                    </div>
                                                </div>
                                                <div class="col-md-4">
                                                    <div class="single-input">
                                                        {{form.gender}}
                                                    </div>
                                                </div>
                                                <div class="col-md-4">
                                                    <div class="single-input">
                                                        {{form.marrital_status}}
                                                    </div>
                                                </div>
                                                <div class="col-md-12">
                                                    <div class="btn-border">
                                                        <button style="margin-top: 30px;" class="cmn-btn" type="submit">Update Profile</button>
                                                    </div>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Dashboard Section end -->

{% endblock content %}

userauths/templates/userauths/sign-in.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<style>
    body {
        background-color: #121212;
        color: #fff;
    }

    .fade-in {
        opacity: 0;
        transform: translateY(20px);
        animation: fadeIn 1s ease-out forwards;
    }

    @keyframes fadeIn {
        to {
            opacity: 1;
            transform: translateY(0);
        }
    }

    .single-input label {
        color: #fff;
    }

    .single-input input {
        transition: all 0.3s ease;
        border: 2px solid transparent;
        background-color: #1e1e1e;
        color: #fff;
    }

    .single-input input::placeholder {
        color: #bbb;
    }

    .single-input input:focus {
        border-color: #bb86fc;
        box-shadow: 0 0 10px rgba(187, 134, 252, 0.5);
    }

    .animated-img {
        width: 650px;
        height: 650px;
        border-radius: 50%;
        object-fit: cover;
        animation: bounce 3s infinite alternate;
    }

    @keyframes bounce {
        0% {
            transform: scale(1);
        }
        100% {
            transform: scale(1.05);
        }
    }

    .login-box {
        background: #1e1e1e;
        padding: 30px;
        border-radius: 10px;
        box-shadow: 0px 0px 15px rgba(255, 255, 255, 0.1);
    }

    .cmn-btn {
        background: linear-gradient(135deg, #bb86fc, #6200ea);
        border: none;
        padding: 10px 20px;
        color: white;
        font-weight: bold;
        border-radius: 5px;
        cursor: pointer;
        transition: all 0.3s ease;
    }

    .cmn-btn:hover {
        background: linear-gradient(135deg, #6200ea, #bb86fc);
        box-shadow: 0px 0px 10px rgba(187, 134, 252, 0.5);
    }

    .forgot-password {
        color: #bb86fc;
        font-weight: bold;
    }

    .title, .dont-acc, .dont-acc a {
        color: #fff;
    }
</style>

<br><br><br>
<section class="login-reg fade-in">
    <div class="overlay pt-120">
        <div class="container">
            <div class="row align-items-center justify-content-center">
                <div class="col-xl-5">
                    <div class="login-box">
                        <div class="section-text text-center fade-in">
                            <h2 class="title">Welcome to Reacto Test</h2>
                            <p class="dont-acc">Don't have an account yet? <a href="{% url 'userauths:sign-up' %}">Sign Up</a></p>
                        </div>

                        {% if messages %}
                            {% for message in messages %}
                                <strong>{{ message }}</strong>
                            {% endfor %}
                        {% endif %}

                        <form method="POST" class="login-form">
                            {% csrf_token %}

                            <div class="row">
                                <div class="col-12">
                                    <div class="single-input">
                                        <label for="logemail">Email*</label>
                                        <input type="text" required name="email" id="logemail" placeholder="Enter Your Email">
                                    </div>
                                    
                                    <div class="single-input">
                                        <label for="logpassword">Password*</label>
                                        <input type="password" required name="password" id="logpassword" placeholder="Enter Your Password">
                                    </div>
                                    <button class="cmn-btn w-100" type="submit">Login</button>
                                    <div class="text-center mt-3">
                                        <a href="#" class="forgot-password">Forgot Password?</a>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<script>
    document.addEventListener("DOMContentLoaded", function() {
        let form = document.querySelector(".login-form");
        form.style.opacity = 0;
        form.style.transform = "translateY(20px)";
        setTimeout(() => {
            form.style.transition = "all 0.8s ease-out";
            form.style.opacity = 1;
            form.style.transform = "translateY(0)";
        }, 500);
    });
</script>
{% endblock content %}